ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.insurancepegtrap]
path = "out/InsurancePegTrap.sol/InsurancePegTrap.json"
response_contract = "0x278fddf3540AD0bA675fCbC705435B8B5cF2f28A"
response_function = "response(address,uint256,string)"
cooldown_period_blocks = 33
min_number_of_operators = 1
max_number_of_operators = 2
block_sample_size = 10
private_trap = true
whitelist = ["0xed0aae28f762b06a432f86fddb8a8a52d2037aa7"]
address = "0x9C43D7D439366403988e15FAcB0Df2903FaAA27a"
